{{ $scheme := "http" }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name}}-console"
  labels:
    app: "{{ .Values.name}"
spec:
  type: {{ .Values.consoleService.type }}
  loadBalancerIP: {{ default "" .Values.consoleService.loadBalancerIP }}
  ports:
    - name: {{ $scheme }}
      port: {{ .Values.consoleService.port }}
      targetPort: {{ .Values.minioConsolePort }}
      protocol: TCP
{{- if .Values.consoleService.externalIPs }}
  externalIPs:
{{- range $i , $ip := .Values.consoleService.externalIPs }}
  - {{ $ip }}
{{- end }}
{{- end }}
  selector:
    app: "{{ .Values.name}"
