apiVersion: apps/v1
kind: Deployment
metadata:
 name: "{{ .Values.minio.name }}"
 namespace: "{{ .Values.global.namespace }}"
 labels:
    app: "{{ .Values.minio.name }}"
    version: "{{ .Values.global.version }}"
 annotations: 
    build-date: "{{ .Values.global.buildDate }}"
    template-version: "{{ .Values.global.templateVersion }}"
spec:
 strategy:
   type: Recreate
 selector:
   matchLabels:
     app: "{{ .Values.minio.name }}"
 template:
   metadata:
     labels:
       app: "{{ .Values.minio.name }}"
   spec:
     containers:
       - name: "{{ .Values.minio.name }}"
         image: "{{ .Values.minio.image }}"         
         args:
         - server
         - /data
         resources:
           requests:
             cpu: "250m"
             memory: 500Mi
           limits:
             cpu: "500m"
             memory: 1Gi
         ports:
          - containerPort: 9000
         env:
          - name: "MINIO_ROOT_USER"
            value: "{{ .Values.env.accessKey }}" 
          - name: "MINIO_ROOT_PASSWORD"
            value: "{{ .Values.env.secretKey }}"
         volumeMounts:
           - mountPath: "{{ .Values.mountPath }}"
             name: "{{ .Values.volumes.name }}"
     volumes:
       - name: "{{ .Values.volumes.name }}"
         persistentVolumeClaim:
           claimName: minio-pv-claim
