{{ $scheme := "http" }}
apiVersion: apps/v1
kind: Deployment
metadata:
 name: "{{ .Values.name }}"
 labels:
    app: "{{ .Values.name }}"
spec:
 strategy:
   type: Recreate
 selector:
   matchLabels:
     app: "{{ .Values.name }}"
 template:
   metadata:
     labels:
       app: "{{ .Values.name }}"
   spec:
     containers:
       - name: "{{ .Values.name }}"
         image: "{{ .Values.minio.image }}"         
         args:
         - server
         - /data
         resources:
           requests:
             cpu: "250m"
             memory: 500Mi
           limits:
             cpu: "500m"
             memory: 1Gi
         ports:
            - name: {{$scheme}}
              containerPort: 9000
            #- name: {{$scheme}}
              containerPort: 9001
         env:
          - name: "MINIO_ROOT_USER"
            value: "{{ .Values.env.accessKey }}" 
          - name: "MINIO_ROOT_PASSWORD"
            value: "{{ .Values.env.secretKey }}"
         volumeMounts:
           - mountPath: "{{ .Values.mountPath }}"
             name: "{{ .Values.volumes.name }}"
     volumes:
       - name: "{{ .Values.volumes.name }}"
         persistentVolumeClaim:
           claimName: "{{ .Values.persistentVolumeClaim.claimName }}"
