apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{.Values.persistentVolumeClaim.claimName}}"
spec:
  storageClassName: "{{.Values.persistence.storageClass}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{.Values.persistence.size}}"
