kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{.Values.persistentVolumeClaim.claimName}}"
spec:
  storageClassName: "{{.Values.persistence.storageClass}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{.Values.persistence.size}}"

