apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
spec:
  storageClassName: "{{.Values.persistence.storageClass}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{.Values.persistence.size}}"
