apiVersion: v1
data:
  openssl.conf: W3JlcV0KZGlzdGluZ3Vpc2hlZF9uYW1lID0gcmVxX2Rpc3Rpbmd1aXNoZWRfbmFtZQp4NTA5X2V4dGVuc2lvbnMgPSB2M19yZXEKcHJvbXB0ID0gbm8KCltyZXFfZGlzdGluZ3Vpc2hlZF9uYW1lXQpDID0gVVMKU1QgPSBWQQpMID0gU29tZXdoZXJlCk8gPSBNeU9yZwpPVSA9IE15T1UKQ04gPSBNeVNlcnZlck5hbWUKClt2M19yZXFdCnN1YmplY3RBbHROYW1lID0gQGFsdF9uYW1lcwoKW2FsdF9uYW1lc10KSVAuMSA9IDEyNy4wLjAuMQpETlMuMSA9IGxvY2FsaG9zdAoK
  private.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdkYWVYQXNjdGlJMTBQOG91RzBvR2NXTmhYWmNPMG0vUGNKY1RGZkVEUVJvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFdW43ZmVDajRsRUZaRGRiMmVIR1FSaStudjdtRzU5WXRrc1VNRndKYVBrSmtPWTh0eDVHSgpVaEV0TEFUdGs4N05LQXJTZlNGL1NvaDVLZ0MvU2JtMVdBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: tls-ssl-minio
type: Opaque
