apiVersion: v1
kind: Service
metadata:
  name:  "{{ .Values.minio.name}}--service"
  namespace: "{{ .Values.global.namespace }}"
  labels:
    app: "{{ .Values.minio.name}}"
    version: "{{ .Values.global.version}}"
  annotations: 
    build-date: "{{ .Values.global.buildDate }}"
    template-version: "{{ .Values.global.templateVersion }}"
spec:
  selector:
    app: "{{ .Values.minio.name}}"
  ports:
    - port: 9000
      targetPort: 9000
  type: "{{ .Values.service.type}}"
